version: '3'
services:
  mysql:
    image: mysql:8
    env_file:
      - .mysql.env
    volumes:
        - mysql:/var/lib/mysql   
    ports:
      - "3306:3306"
    deploy:
      mode: replicated
      replicas: 1
volumes:
  mysql:
